language: node_js
node_js:
    - "11.6.0"
script:
    - npm i -g truffle
    - npm i -g solium
    - npm i -g etherscan-uploader
    - truffle compile && solium -d contracts/
    - npm run build
    - sudo apt-get install jq
    - etherscan-uploader -f ./contracts/Exploitable.sol -a $(jq -r ".RINKEBY_TEST.EXPLOITABLE" .src/config.json) -n Exploitable -e rinkeby -k $ETHERSCAN_TOKEN -c "address payable" -v $(jq -r ".RINKEBY_TEST.NEGOTIATOR" ./src/config.json)
deploy:
    local-dir: ./dist
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    repo: 0xdefaceme/www
    fqdn: 0xdeface.me
    target-branch: master
    on:
        branch: master
